# tasks to complete before running roles
- tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (fedora)
      tags: always
      yum: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Fedora"

# run roles
- tags: base
  become: true
  roles:
    - linux-general-setup

# end of run cleanup and reporting
- become: true
  tasks:
  - name: cleanup package cache (fedora)
    tags: always
    yum:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Fedora"]

  - name: autoremove orphan packages (fedora)
    tags: always
    yum:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Fedora"]
