- name: ansible setup | ensure ansible is the latest version
  tags: ansible,ansible-setup
  package:
    name: ansible
    state: latest

- name: ansible setup | install required packages
  tags: ansible,ansible-setup,packages
  package:
    name:
      - python-psutil

- name: ansible setup | remove default ansible directory (/etc/ansible) from host
  tags: ansible,ansible-setup
  file:
    path: /etc/ansible
    state: absent

# - name: ansible setup | generate provision script from template
#  tags: ansible,ansible-setup,scripts
#  template:
#    src: provision.sh.j2
#    dest: /usr/local/bin/provision
#    owner: root
#    group: root
#    mode: 0755
