---
# This playbook contains common plays that will be run on all nodes.

- name: install delta RPMs support
  yum:
    name: 'deltarpm'
    state: latest
  become: true

- name: upgrade all packages
  yum:
    name: '*'
    state: latest                                                                                                                                         
  become: true

- block:
  - import_tasks: ansible_setup.yml

  # install software
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_utilities.yml


  rescue:
    - set_fact: task_failed=true
